#include "draw.h"
#include <cstdlib>
#include <stdio.h>
#include <unistd.h>
#include <ctype.h>
#include <stdlib.h>
#include <thread>
#include <cstdio>
#include <fcntl.h>
#include <dirent.h>
#include <pthread.h>
#include <fstream>
#include <time.h>
#include <malloc.h>
#include <iostream>
#include <fstream>
#include <ctime>
#include <cmath>
#include <sstream>
#include <iomanip>
#include <chrono>
#include <vector>
#include <mutex>
#include <functional>
#include <signal.h>
#include <stdbool.h>
#include <unordered_map>
// 普通函数调用
#include <string.h>
#include <cstring>
#include <string>
// string函数调用
#include <sys/time.h>
#include <sys/select.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <linux/input.h>
#include <linux/uinput.h>
#include <sys/utsname.h>
// sys linux函数调用
#include <thread>
#include <cstdint>
#include <stdio.h>
#include <mutex>